#!/bin/bash
echo "Hi, Master $USER"
echo "Let me install the things you need."

# functions
function exists() {
	if ! command -v $1 &> /dev/null;
		then echo 1;
		else echo 0;
	fi
}

function exitIfError() {
	if [[ $1 -ne 0 ]]; then 
		echo "Error occured" 
		exit 
	fi
}

function alreadyInstalled() {
	echo "Already installed, skipping";
}

if [[ $(exists apt) -ne 0 ]]; then
	echo "Yo, booooi. Only debian based"
      	exit 1
fi

echo "Starting...."
echo "Installing fish..."
if [[ $(exists fish) -ne 0 ]];
then
	sudo apt install fish -y
	exitIfError $?
else
	alreadyInstalled
fi

echo "Installing omf..."
if [[ ! -f "$HOME/.config/omf/bundle" ]];
then
	wget https://get.oh-my.fish -O /tmp/installomf
	exitIfError $?
	chmod +x /tmp/installomf
	fish -c "/tmp/installomf --noninteractive"
	rm -rf /tmp/installomf
else
	alreadyInstalled
fi

echo "Installing nvm..."
if [[ ! -d "$HOME/.nvm" ]];
then
	fish -c "omf install nvm"
	exitIfError $?
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
	exitIfError $?
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
else
	alreadyInstalled
fi

echo "Install node using nvm"
if [[ $(exists node) -ne 0 ]];
then
	nvm install node
	nvm alias default node
	nvm use default
	exitIfError $?
else
	alreadyInstalled
fi




source ~/.bashrc
echo "Finished"
