#!/bin/bash

url=""
path="~/Music"
format="%(title)s.mp3"

if [ -z "$1" ]; then
    echo "No url supplied";
    exit 1;
fi

url="$1"

if [ -z "$2" ]; then
    echo "using default path";
else
    path="$2"
fi

youtube-dl -f 'bestaudio' $url -o "$path/$format"