#!/bin/bash

url=""
path="~/Music"

if [ -z "$1" ]; then
    echo "No url supplied";
    exit 1;
fi

url="$1"

if [ -z "$2" ]; then
    echo "Saving in $path"
else
    path="$2"
fi

name=$(ytdl "$url" --info | head -n 1 | cut -d":" -f2 | sed -e 's/^[[:space:]]*//')
cd $path
ytdl "$url" | ffmpeg -i pipe:0 -b:a 192K -vn "$name.mp3"

