#!/bin/bash

# Bus ID of the PCI express controller
CONTROLLER_BUS_ID=0000:00:01.0

# Bus ID of the graphic card
DEVICE_BUS_ID=0000:01:00.0

echo 'Turning the PCIe controller on to allow card rescan'
sudo tee /sys/bus/pci/devices/${CONTROLLER_BUS_ID}/power/control <<<on

echo 'Waiting 1 second'
sleep 1

if [[ ! -d /sys/bus/pci/devices/${DEVICE_BUS_ID} ]]; then
    echo 'Rescanning PCI devices'
    sudo tee /sys/bus/pci/rescan <<<1
    echo "Waiting 15 second for rescan"
    sleep 15
fi

echo 'Turning the card on'
sudo tee /sys/bus/pci/devices/${DEVICE_BUS_ID}/power/control <<<on
